name: Regression Testing

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  scanning:
    uses: callmegreg-demo-org/reusable-security-workflows/.github/workflows/strict-security-scan.yml@3393944a9f401f8d62d420a32befdc071ac2787a # main
    secrets: inherit
